config/routes.rb
Rails.application.routes.draw do

  get 'columns/edit'

  get 'columns/create'

  get 'columns/destroy'

  devise_for :users

  get 'welcome/index'

  get 'welcome/about'

  get 'ratings/create'

  get 'ratings/destroy'

  get 'reviews/create'

  get 'reviews/new'

  get 'reviews/destroy'

  get 'items/show'

  get 'items/_new'

  get 'items/edit'

  get 'items/create'

  get 'items/update'

  get 'items/destroy'

  get 'users/update'

  get 'users/show'

  get 'sheets/index'

  get 'sheets/show'

  get 'sheets/new'

  get 'sheets/edit'

  post 'sheets/create'

  get 'sheets/update'

  get 'sheets/destroy'

  resources :sheets do
    resources :items
  end

  resources :columns

  root to: 'welcome#index'

end

app/models/column.rb
class Column < ActiveRecord::Base
  belongs_to :sheet

end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
  has_many :items, dependent: :destroy
  has_many :columns, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  def edit
  end

  def create
    @sheet = Sheet.find(params[:sheet_id])
    @columns = @sheet.columns

    @column = Column.new(column_params)
    @column.sheet = @sheet

    respond_to do |format|
      format.html
      format.js
    end

  end

  def destroy
  end

  private

  def column_params
    params.require(:column).permit(:title)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
  end

  def destroy
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
  end

  def new
  end

  def destroy
  end
end

app/controllers/sheets_controller.rb
class SheetsController < ApplicationController
  def index
    @sheets = Sheet.all
  end
  
  def show
    @sheet = Sheet.find(params[:id])
    @columns = @sheet.columns.all
  end

  def new
    @sheet = Sheet.new
  end

  def edit
  end

  def create
    @sheet = Sheet.new(sheet_params)

    column_params.each do |value|
      @sheet.columns.build(value.permit(:title, :data_type))
    end

    if @sheet.save
      redirect_to @sheet
    else
      flash[:error] = "Error saving sheet."
      render :new
    end
  end

  def update
    @sheet = Sheet.find(params[:id])
  end

  def destroy
    @sheet = Sheet.find(params[:id])
  end

  private

  def sheet_params
    params.require(:sheet).permit(:title, :description, :created_at, :updated_at, :column)
  end

  def column_params
    params.require(:column)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def update
  end

  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/columns/create.html.erb
<h1>Columns#create</h1>
<p>Find me in app/views/columns/create.html.erb</p>

app/views/columns/destroy.html.erb
<h1>Columns#destroy</h1>
<p>Find me in app/views/columns/destroy.html.erb</p>

app/views/columns/edit.html.erb
<h1>Columns#edit</h1>
<p>Find me in app/views/columns/edit.html.erb</p>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/new.html.erb
<!-- Modal -->
<div class="modal fade" id="newItem" tabindex="-1" role="dialog" aria-labelledby="newItemLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Item</h4>
      </div>
      <div class="modal-body">
        
        <table class="table">

        <!-- TEMPORARY Item Entry -->
          <tr>
            <th>Make</th>
            <th>Model</th>
            <th>Screen Size (Inches)</th>
            <th>Weight (Pounds)</th>
            <th>CPU Speed (GHz)</th>
            <th>RAM (GB)</th>
            <th>HDD (GB)</th>
          </tr>
          <tr>
            <td>Lenovo</td>
            <td>T410</td>
            <td>14</td>
            <td>6</td>
            <td>2.53</td>
            <td>3.6</td>
            <td>120</td>
          </tr>
        </table>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Specsheet</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <ul class="nav nav-tabs">
    <li><%= link_to "Specsheet", welcome_index_path %></li>
    <li><%= link_to "About", welcome_about_path %></li>
    <li><%= link_to "View Sheets", sheets_index_path %></li>
    <li><%= link_to "Create New Sheet", sheets_new_path %></li>
      <div class="pull-right user-info">
        <% if current_user %>
          Hello <%=current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>

  <%= yield %>
  </div>
</body>
</html>

app/views/ratings/create.html.erb
<h1>Ratings#create</h1>
<p>Find me in app/views/ratings/create.html.erb</p>

app/views/ratings/destroy.html.erb
<h1>Ratings#destroy</h1>
<p>Find me in app/views/ratings/destroy.html.erb</p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/sheets/_column_form.html.erb
<% form_for [Column.new], :url => {:action => :create, :controller => :columns} do |f| %>
  <div class="col-lg-6">
    <div class="input-group">
      <span class="input-group-addon" id="sizing-addon1">Column Heading:</span>
      <%= f.text_field :title, class: 'form-control', placeholder: "Heading goes here." %>
    </div><!-- /input-group -->
  </div><!-- /.col-lg-6 -->

  <div class="col-lg-6">
    <div class="input-group">
      <input type="text" class="form-control" aria-label="...">
      <div class="input-group-btn">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Data Type <span class="caret"></span></button>
        <ul class="dropdown-menu dropdown-menu-right" role="menu">
          <li><a href="#">Text</a></li>
          <li><a href="#">Number</a></li>
          <li><a href="#">Link</a></li>
          <li class="divider"></li>
          <li><a href="#">Preset Choices (Dropdown List)</a></li>
        </ul>
      </div>
    </div>
  </div>
<br>
<% end %>

app/views/sheets/destroy.html.erb
<h1>Sheets#destroy</h1>
<p>Find me in app/views/sheets/destroy.html.erb</p>

app/views/sheets/edit.html.erb
<h1>Sheets#edit</h1>
<p>Find me in app/views/sheets/edit.html.erb</p>

app/views/sheets/index.html.erb
<h1>Specsheets</h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title pull-left" style="padding-top: 7.5px;">All Specsheets</h4>
      <div class="input-group">
        <input class="form-control" placeholder="Search for a sheet..." type:"text">
        <div class="input-group-btn">
          <button class="btn btn-primary"><i class="glyphicon-search"></i></button>
        </div>
      </div>
    </div>

  </div>
    <table class="table">
      <% @sheets.each do |sheet| %>
        <tr>
          <td><%= sheet.id %></td>
          <td><%= link_to sheet.title, sheet %></td>
          <td>
          <% if @items %>
            <%= "item count" =%>
          <% else %>
            <%= "Nothing Yet!" %>
          <% end %>
          </td>
          <td>number of reviews</td>
        </tr>
      <% end %>

    </table>

app/views/sheets/new.html.erb
<h1>Create a New Specsheet</h1>
  <script type="text/javascript"></script>
  <%= form_for Sheet.new, :url => {:action => :create, :controller => :sheets} do |f| %>
    <%= f.text_field :title, class: 'form-control', placeholder: " Sheet Title" %>
    </br>
    <%= f.text_field :description, class: 'form-control', placeholder: "Sheet Description" %>
    </br>
    <div id="dynamicInput">
      <div class="row">
        <div class="col-xs-6">
          <input class="form-control" id="sheet_column_title" name="column[][title]" placeholder="Column Title" type="text">
        </div>
        <div class="col-xs-6">
          <input class="form-control" id="sheet_column_data_type" name="column[][data_type]" placeholder="Data Type (Numbers, Words, yes/no)" type="text">
        </div>
      </div>
    </div>
    </br>
    <input class="btn btn-default" type="button" value="Add Column" onClick="addInput('dynamicInput')">
    <%= f.submit "Save Specsheet!", class: 'btn btn-default' %>
  <% end %>
  </div>
</div>

app/views/sheets/show.html.erb
<h1><%= @sheet.title %></h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <button type="submit" class="btn btn-default col-xs-1" data-toggle="modal" data-target="#newItem">Add Item</button>
    <div class="input-group col-s-3">
      <input class="form-control" placeholder="Search for an item..." type:"text">
      <div class="input-group-btn">
        <button class="btn btn-primary"><i class="glyphicon-search"></i></button>
      </div>
    </div>
  </div>
  <% if @sheet.description %>
    <div class="panel-body">
      <p><%= @sheet.description %></p>
    </div>
  <% end %>
</div>
    <table class="table">

      <tr>
        <% @sheet.columns.each do |col|%>
          <th><%= col.title =%></th>
        <% end %>
      </tr>
      <tr>
        <% @sheet.columns.each do |col|%>
          <td><%= col.data_type =%></td>
        <% end %>
      </tr>
    </table>

<!-- Modal THIS SHOULD BE A PARTIAL IN ITEMS/NEW - I think -->

<div class="modal fade modal-lg-backdrop" id="newItem" tabindex="-1" role="dialog" aria-labelledby="newItemLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Item</h4>
      </div>
        <table class="table">

        <!-- TEMPORARY Item Entry -->
          <tr>
            <th>Make</th>
            <th>Model</th>
            <th>Screen Size (Inches)</th>
            <th>Weight (Pounds)</th>
            <th>CPU Speed (GHz)</th>
            <th>RAM (GB)</th>
            <th>HDD (GB)</th>
          </tr>
          <tr>
            <td>
              <div class="input-group">
                <input type="text" class="form-control" aria-label="...">
              </div><!-- /input-group -->
            </td>
            <td>T410</td>
            <td>14</td>
            <td>6</td>
            <td>2.53</td>
            <td>3.6</td>
            <td>120</td>
          </tr>
        </table>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/sheets/update.html.erb
<h1>Sheets#update</h1>
<p>Find me in app/views/sheets/update.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome to Specsheet!</h1>
<p>What you see here is the finest web app ever conceived.</p>
<p>Well... It WILL be. Soon. See you later!</p>